---
apiVersion: v1
kind: Service
metadata:
 name: stars
 labels:
   app: stars
spec:
 type: NodePort
 ports:
 - port: 8080
   nodePort: 32718
   protocol: TCP
 selector:
   app: stars
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stars-deploy
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: stars
    spec: 
      containers:
      - name: stars-pod
        image: myregistry:5000/stars:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: config
              key: environment
        - name: MONGO_ENABLED
          value: "true"