version: '3.3'

services:
  app:
    image: ${IMAGE:-stars:latest}
    links:
      - mongo
    environment:
      - MONGO_ENABLED=true
      - MONGO_SERVICE_URI=mongodb://mongo:27017/stars
      - MONGO_COLLECTION=stars
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
